# Generated by Django 4.2 on 2023-04-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_userrequestcounttrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequestcounttrack',
            old_name='count',
            new_name='request_count',
        ),
    ]
