# Generated by Django 4.2 on 2023-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('mobile', 'Mobile'), ('other', 'Other')], default='home', max_length=10),
            preserve_default=False,
        ),
    ]
